
/*
 * app_tasks.c
 * Alarm Watch - FreeRTOS Level 4
 * STM32F411 Discovery
 * CMSIS-RTOS V2
 */

#include "app_tasks.h"
#include "main.h"
#include "cmsis_os2.h"

#include "keypad.h"
#include "ds3231.h"
#include "lcd1602.h"
#include "uart_debug.h"

#include <stdio.h>
#include <string.h>

/* Peripheral handles generated by CubeMX */
extern UART_HandleTypeDef huart2;
extern I2C_HandleTypeDef hi2c1;
extern I2C_HandleTypeDef hi2c3;

/* ================================
 * Application Events
 * ================================ */

typedef enum
{
    EVENT_KEY,
    EVENT_RTC,
    EVENT_RTC_ERROR
} AppEventType;

typedef struct
{
    AppEventType type;

    union
    {
        char key;
        DS3231_DateTime datetime;
    } data;

} AppEvent;

/* ================================
 * RTOS Handles
 * ================================ */

static osMessageQueueId_t eventQueue = NULL;
static osMutexId_t rtcMutex = NULL;

static osThreadId_t keypadHandle = NULL;
static osThreadId_t rtcHandle = NULL;
static osThreadId_t controllerHandle = NULL;
static osThreadId_t displayHandle = NULL;
static osThreadId_t ledHandle = NULL;

/* ================================
 * Shared RTC Data
 * ================================ */

static DS3231_DateTime sharedDateTime = {0};
static uint8_t sharedRtcValid = 0;

/* ================================
 * Task Prototypes
 * ================================ */

static void KeypadTask(void *argument);
static void RtcTask(void *argument);
static void ControllerTask(void *argument);
static void DisplayTask(void *argument);
static void LedTask(void *argument);

/* ================================
 * Keypad Task
 * ================================ */

static void KeypadTask(void *argument)
{
    (void)argument;

    Keypad_Init();

    for (;;)
    {
        char key = Keypad_Read();

        if (key != '\0')
        {
            AppEvent event = {0};

            event.type = EVENT_KEY;
            event.data.key = key;

            if (osMessageQueuePut(
                    eventQueue,
                    &event,
                    0,
                    0) != osOK)
            {
                /* Queue full: event dropped */
            }
        }

        osDelay(1);
    }
}

/* ================================
 * RTC Task
 * ================================ */

static void RtcTask(void *argument)
{
    (void)argument;

    uint32_t period = osKernelGetTickFreq() / 4U;
    uint32_t nextWake = osKernelGetTickCount();

    if (period == 0U)
        period = 1U;

    for (;;)
    {
        DS3231_DateTime datetime = {0};
        uint8_t valid = 0;
        AppEvent event = {0};

        HAL_StatusTypeDef status =
            DS3231_TimeValid(&valid);

        if (status == HAL_OK && valid)
        {
            status = DS3231_Read(&datetime);
        }

        if (status == HAL_OK && valid)
        {
            event.type = EVENT_RTC;
            event.data.datetime = datetime;
        }
        else
        {
            event.type = EVENT_RTC_ERROR;
        }

        if (osMessageQueuePut(
                eventQueue,
                &event,
                0,
                0) != osOK)
        {
            /* Queue full: event dropped */
        }

        nextWake += period;
        if (osDelayUntil(nextWake) != osOK)
        {
            /* Deadline missed: resynchronize */
            nextWake = osKernelGetTickCount();
        }
    }
}

/* ================================
 * Controller Task
 * ================================ */

static void ControllerTask(void *argument)
{
    (void)argument;

    AppEvent event;

    int lastSecond = -1;
    uint8_t rtcErrorReported = 0;

    for (;;)
    {
        osStatus_t status = osMessageQueueGet(
            eventQueue,
            &event,
            NULL,
            osWaitForever
        );

        if (status != osOK)
            continue;

        switch (event.type)
        {
            case EVENT_KEY:
            {
                UART_Debug_Log(
                    UART_LOG_INFO,
                    "[KEY] %c\r\n",
                    event.data.key
                );
                break;
            }

            case EVENT_RTC:
            {
                DS3231_DateTime *t =
                    &event.data.datetime;

                /* Update shared datetime */
                if (osMutexAcquire(
                        rtcMutex,
                        osWaitForever) == osOK)
                {
                    sharedDateTime = *t;
                    sharedRtcValid = 1;

                    osMutexRelease(rtcMutex);
                }

                rtcErrorReported = 0;

                /* Log only when second changes */
                if (lastSecond != (int)t->second)
                {
                    lastSecond = t->second;

                    UART_Debug_Log(
                        UART_LOG_INFO,
                        "[RTC] %02u:%02u:%02u "
                        "%02u/%02u/%04u\r\n",
                        (unsigned)t->hour,
                        (unsigned)t->minute,
                        (unsigned)t->second,
                        (unsigned)t->date,
                        (unsigned)t->month,
                        (unsigned)t->year
                    );
                }
                break;
            }

            case EVENT_RTC_ERROR:
            {
                if (osMutexAcquire(
                        rtcMutex,
                        osWaitForever) == osOK)
                {
                    sharedRtcValid = 0;
                    osMutexRelease(rtcMutex);
                }

                lastSecond = -1;

                if (!rtcErrorReported)
                {
                    UART_Debug_Log(
                        UART_LOG_ERROR,
                        "[RTC] Read error or "
                        "invalid time\r\n"
                    );

                    rtcErrorReported = 1;
                }
                break;
            }

            default:
                break;
        }
    }
}

/* ================================
 * Display Task
 * ================================ */

static void DisplayTask(void *argument)
{
    (void)argument;

    char line1[17];
    char line2[17];

    char previousLine1[17] = {0};
    char previousLine2[17] = {0};

    DS3231_DateTime localTime;
    uint8_t valid;

    uint8_t lcdReady = 0;

    for (;;)
    {
        /* Initialize or recover LCD */
        if (!lcdReady)
        {
            if (LCD_Init(&hi2c1) == HAL_OK)
            {
                lcdReady = 1;

                /* Force both lines to refresh */
                previousLine1[0] = '\0';
                previousLine2[0] = '\0';
            }
            else
            {
                osDelay(2000);
                continue;
            }
        }

        /* Copy shared RTC data safely */
        valid = 0;
        memset(&localTime, 0, sizeof(localTime));

        if (osMutexAcquire(
                rtcMutex,
                osWaitForever) == osOK)
        {
            localTime = sharedDateTime;
            valid = sharedRtcValid;

            osMutexRelease(rtcMutex);
        }

        /* Prepare LCD content */
        if (valid)
        {
            snprintf(
                line1,
                sizeof(line1),
                "%02u:%02u:%02u",
                (unsigned)localTime.hour,
                (unsigned)localTime.minute,
                (unsigned)localTime.second
            );

            snprintf(
                line2,
                sizeof(line2),
                "%02u/%02u/%04u",
                (unsigned)localTime.date,
                (unsigned)localTime.month,
                (unsigned)localTime.year
            );
        }
        else
        {
            snprintf(
                line1,
                sizeof(line1),
                "RTC ERROR"
            );

            snprintf(
                line2,
                sizeof(line2),
                "CHECK DS3231"
            );
        }

        /* Update only changed LCD lines */
        if (strcmp(line1, previousLine1) != 0)
        {
            if (LCD_PrintLine(0, line1) == HAL_OK)
            {
                strcpy(previousLine1, line1);
            }
            else
            {
                lcdReady = 0;
            }
        }

        if (lcdReady &&
            strcmp(line2, previousLine2) != 0)
        {
            if (LCD_PrintLine(1, line2) == HAL_OK)
            {
                strcpy(previousLine2, line2);
            }
            else
            {
                lcdReady = 0;
            }
        }

        osDelay(250);
    }
}

/* ================================
 * LED Task
 * ================================ */

static void LedTask(void *argument)
{
    (void)argument;

    for (;;)
    {
        HAL_GPIO_TogglePin(
            ALARM_LED_GPIO_Port,
            ALARM_LED_Pin
        );

        osDelay(500);
    }
}

/* ================================
 * Initialize application tasks
 * ================================ */

void AppTasks_Init(void)
{
    /* Initialize drivers */
    UART_Debug_Init(&huart2);
    UART_Debug_SetLevel(UART_LOG_INFO);

    DS3231_Init(&hi2c3);

    /* Create event queue */
    eventQueue = osMessageQueueNew(
        16,
        sizeof(AppEvent),
        NULL
    );

    if (eventQueue == NULL)
        Error_Handler();

    /* Create mutex */
    rtcMutex = osMutexNew(NULL);

    if (rtcMutex == NULL)
        Error_Handler();

    /* Task attributes */
    const osThreadAttr_t keypadAttr = {
        .name = "KeypadTask",
        .priority = osPriorityNormal,
        .stack_size = 1024
    };

    const osThreadAttr_t rtcAttr = {
        .name = "RtcTask",
        .priority = osPriorityNormal,
        .stack_size = 1024
    };

    const osThreadAttr_t controllerAttr = {
        .name = "ControllerTask",
        .priority = osPriorityAboveNormal,
        .stack_size = 1536
    };

    const osThreadAttr_t displayAttr = {
        .name = "DisplayTask",
        .priority = osPriorityBelowNormal,
        .stack_size = 1536
    };

    const osThreadAttr_t ledAttr = {
        .name = "LedTask",
        .priority = osPriorityLow,
        .stack_size = 512
    };

    /* Create tasks */
    controllerHandle = osThreadNew(
        ControllerTask,
        NULL,
        &controllerAttr
    );

    keypadHandle = osThreadNew(
        KeypadTask,
        NULL,
        &keypadAttr
    );

    rtcHandle = osThreadNew(
        RtcTask,
        NULL,
        &rtcAttr
    );

    displayHandle = osThreadNew(
        DisplayTask,
        NULL,
        &displayAttr
    );

    ledHandle = osThreadNew(
        LedTask,
        NULL,
        &ledAttr
    );

    /* Validate task creation */
    if (controllerHandle == NULL ||
        keypadHandle == NULL ||
        rtcHandle == NULL ||
        displayHandle == NULL ||
        ledHandle == NULL)
    {
        Error_Handler();
    }
}
